export const FETCH_AUTH = "FETCH_AUTH";
export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_UI_ELEMENTS = "FETCH_UI_ELEMENTS";
export const FETCH_FILE_UPLOAD = "FETCH_FILE_UPLOAD";
export const FETCH_SLIDES = "FETCH_SLIDES";
export const FETCH_UPDATE_SLIDE = "FETCH_UPDATE_SLIDE";
export const FETCH_REMOVE_SLIDE = "FETCH_REMOVE_SLIDE";
export const FETCH_ADD_SLIDE = "FETCH_ADD_SLIDE";
